#pragma config(Sensor, S1,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float rl;

float X=3;float Y=19;int dir;bool L;bool R;float BX=3;float BY=2;int BN=1;float c1X=2;float c1Y=47;int c1dir=0;float c1BX=2;float c1BY=47;float c1BN=-2;int turn=0;bool c1mve=false;bool c1T;bool c1R;bool c1B;bool c1L;
bool c1turn;int XD1;
float c2X=97;float c2Y=47;int c2dir=4;float c2BX=500;float c2BY=47;float c2BN=0;bool c2mve=false;bool c2T;bool c2R;bool c2B;bool c2L;
bool c2turn;int XD2;
float c3X=97;float c3Y=7;int c3dir=4;float c3BX=500;float c3BY=47;float c3BN=0;bool c3mve=false;bool c3T;bool c3R;bool c3B;bool c3L;
bool c3turn;int XD3;

int killer=-1000;

float h1X=random(100);
float h1Y=random(53);
float h2X=random(100);
float h2Y=random(53);





bool a11=false;bool a12=false;bool a13=true;bool a14=true;bool a15=true;bool a16=true;bool a17=true;bool a18=true;bool a19=true;bool a110=true;
bool a111=true;
bool a112=true;
bool a113=true;
bool a114=true;
bool a115=true;
bool a116=true;
bool a117=true;
bool a118=true;
bool a119=false;
bool a120=false;
bool a21=false;
bool a22=true;
bool a23=true;
bool a24=true;
bool a25=true;
bool a26=true;
bool a27=true;
bool a28=true;
bool a29=true;
bool a210=true;
bool a211=true;
bool a212=true;
bool a213=true;
bool a214=true;
bool a215=true;
bool a216=true;
bool a217=true;
bool a218=true;
bool a219=true;
bool a220=false;
bool a31=true;
bool a32=true;
bool a33=true;
bool a34=true;
bool a35=true;
bool a36=true;
bool a37=true;
bool a38=true;
bool a39=true;
bool a310=true;
bool a311=true;
bool a312=true;
bool a313=true;
bool a314=true;
bool a315=true;
bool a316=true;
bool a317=true;
bool a318=true;
bool a319=true;
bool a320=true;
bool a41=true;
bool a42=true;
bool a43=true;
bool a44=true;
bool a45=true;
bool a46=true;
bool a47=true;
bool a48=true;
bool a49=true;
bool a410=true;
bool a411=true;
bool a412=true;
bool a413=true;
bool a414=true;
bool a415=true;
bool a416=true;
bool a417=true;
bool a418=true;
bool a419=true;
bool a420=true;
bool a51=true;
bool a52=true;
bool a53=true;
bool a54=true;
bool a55=true;
bool a56=true;
bool a57=true;
bool a58=true;
bool a59=true;
bool a510=true;
bool a511=true;
bool a512=true;
bool a513=true;
bool a514=true;
bool a515=true;
bool a516=true;
bool a517=true;
bool a518=true;
bool a519=true;
bool a520=true;
bool a61=true;
bool a62=true;
bool a63=true;
bool a64=true;
bool a65=true;
bool a66=true;
bool a67=true;
bool a68=true;
bool a69=true;
bool a610=true;
bool a611=true;
bool a612=true;
bool a613=true;
bool a614=true;
bool a615=true;
bool a616=true;
bool a617=true;
bool a618=true;
bool a619=true;
bool a620=true;
bool a71=true;
bool a72=true;
bool a73=true;
bool a74=true;
bool a75=true;
bool a76=true;
bool a77=true;
bool a78=true;
bool a79=true;
bool a710=true;
bool a711=true;
bool a712=true;
bool a713=true;
bool a714=true;
bool a715=true;
bool a716=true;
bool a717=true;
bool a718=true;
bool a719=true;
bool a720=true;
bool a81=true;
bool a82=true;
bool a83=true;
bool a84=true;
bool a85=true;
bool a86=true;
bool a87=true;
bool a88=true;
bool a89=true;
bool a810=true;
bool a811=true;
bool a812=true;
bool a813=true;
bool a814=true;
bool a815=true;
bool a816=true;
bool a817=true;
bool a818=true;
bool a819=true;
bool a820=true;
bool a91=true;
bool a92=true;
bool a93=true;
bool a94=true;
bool a95=true;
bool a96=true;
bool a97=true;
bool a98=true;
bool a99=true;
bool a910=true;
bool a911=true;
bool a912=true;
bool a913=true;
bool a914=true;
bool a915=true;
bool a916=true;
bool a917=true;
bool a918=true;
bool a919=true;
bool a920=true;
bool a101=false;
bool a102=true;
bool a103=true;
bool a104=true;
bool a105=true;
bool a106=true;
bool a107=true;
bool a108=true;
bool a109=true;
bool a1010=true;
bool a1011=true;
bool a1012=true;
bool a1013=true;
bool a1014=true;
bool a1015=true;
bool a1016=true;
bool a1017=true;
bool a1018=true;
bool a1019=true;
bool a1020=false;
bool a111b=false;
bool a112b=false;
bool a113b=true;
bool a114b=true;
bool a115b=true;
bool a116b=true;
bool a117b=true;
bool a118b=true;
bool a119b=true;
bool a1110=true;
bool a1111=true;
bool a1112=true;
bool a1113=true;
bool a1114=true;
bool a1115=true;
bool a1116=true;
bool a1117=true;
bool a1118=true;
bool a1119=false;
bool a1120=false;



void hdb(int X,int Y,bool b1){if(b1==true){nxtFillRect(X+2,Y+2,X-2,Y-2);
if(h1X<=X+2&&h1X>=X-2&&h1Y<=Y+2&&h1Y>=Y-2){nxtClearPixel(X,Y);nxtClearPixel(X-1,Y);nxtClearPixel(X-1,Y-1);
nxtClearPixel(X,Y-1);nxtClearPixel(X+1,Y-1);nxtClearPixel(X+1,Y);nxtClearPixel(X+1,Y+1);nxtClearPixel(X,Y+1);nxtClearPixel(X-1,Y+1);nxtDrawLine(X+1,Y+1,X-1,Y-1);nxtDrawLine(X-1,Y+1,X+1,Y-1);}
if(h2X<=X+2&&h2X>=X-2&&h2Y<=Y+2&&h2Y>=Y-2){nxtClearPixel(X,Y);nxtClearPixel(X-1,Y);nxtClearPixel(X-1,Y-1);
nxtClearPixel(X,Y-1);nxtClearPixel(X+1,Y-1);nxtClearPixel(X+1,Y);nxtClearPixel(X+1,Y+1);nxtClearPixel(X,Y+1);nxtClearPixel(X-1,Y+1);nxtDrawLine(X+1,Y+1,X-1,Y-1);nxtDrawLine(X-1,Y+1,X+1,Y-1);}
if(c1X>=X-7&&c1X<=X&&c1Y>=Y-2&&c1Y<=Y+2){c1R=true;}if(c1X<=X+7&&c1X>=X&&c1Y>=Y-2&&c1Y<=Y+2){c1L=true;}
if(c1X<=X+2&&c1X>=X-2&&c1Y>=Y&&c1Y<=Y+7){c1T=true;}if(c1X<=X+2&&c1X>=X-2&&c1Y>=Y-7&&c1Y<=Y){c1B=true;}
if(c2X>=X-7&&c2X<=X&&c2Y>=Y-2&&c2Y<=Y+2){c2R=true;}if(c2X<=X+7&&c2X>=X&&c2Y>=Y-2&&c2Y<=Y+2){c2L=true;}
if(c2X<=X+2&&c2X>=X-2&&c2Y>=Y&&c2Y<=Y+7){c2T=true;}if(c2X<=X+2&&c2X>=X-2&&c2Y>=Y-7&&c2Y<=Y){c2B=true;}
if(c3X>=X-7&&c3X<=X&&c3Y>=Y-2&&c3Y<=Y+2){c3R=true;}if(c3X<=X+7&&c3X>=X&&c3Y>=Y-2&&c3Y<=Y+2){c3L=true;}
if(c3X<=X+2&&c3X>=X-2&&c3Y>=Y&&c3Y<=Y+7){c3T=true;}if(c3X<=X+2&&c3X>=X-2&&c3Y>=Y-7&&c3Y<=Y){c3B=true;}}}

void drawblocks(int X,int Y,bool b1,bool b2,bool b3,bool b4,bool b5,bool b6,bool b7,bool b8,bool b9,bool b10,bool b11,bool b12,bool b13,bool b14,bool b15,bool b16,bool b17,bool b18,bool b19,bool b20){

  if(Y>=50){b1=b2=false;}

  hdb(X,Y,b1);
    hdb(X+5,Y,b2);
    hdb(X+10,Y,b3);
       hdb(X+15,Y,b4);
hdb(X+20,Y,b5);
 hdb(X+25,Y,b6);
  hdb(X+30,Y,b7);
  hdb(X+35,Y,b8);
  hdb(X+40,Y,b9);
  hdb(X+45,Y,b10);
  hdb(X+50,Y,b11);
  hdb(X+55,Y,b12);
hdb(X+60,Y,b13);
hdb(X+65,Y,b14);
hdb(X+70,Y,b15);
hdb(X+75,Y,b16);
hdb(X+80,Y,b17);
hdb(X+85,Y,b18);
hdb(X+90,Y,b19);
hdb(X+95,Y,b20);
}


bool hbb(int X,int Y,bool b,float BX,float BY,int BN){
  bool q;
  q=b;
if(BN<=50){if(BX<=X+8.9&&BX>=X-8.9&&BY<=Y+3.9&&BY>=Y-3.9||BX<=X+3.9&&BX>=X-3.9&&BY<=Y+8.9&&BY>=Y-8.9){q=false;}}
if(h1X<=X+2&&h1X>=X-2&&h1Y<=Y+2&&h1Y>=Y-2||h2X<=X+2&&h2X>=X-2&&h2Y<=Y+2&&h2Y>=Y-2){q=true;}
return q;
}


void bBlock(int X,int Y,bool b1,bool b2,bool b3,bool b4,bool b5,bool b6,bool b7,bool b8,bool b9,bool b10,bool b11,bool b12,bool b13,bool b14,bool b15,bool b16,bool b17,bool b18,bool b19,bool b20,float BX,float BY,int BN,int w)
{

b1=hbb(X,Y,b1,BX,BY,BN);
b2=hbb(X+5,Y,b2,BX,BY,BN);
b3=hbb(X+10,Y,b3,BX,BY,BN);
b4=hbb(X+15,Y,b4,BX,BY,BN);
b5=hbb(X+20,Y,b5,BX,BY,BN);
b6=hbb(X+25,Y,b6,BX,BY,BN);
b7=hbb(X+30,Y,b7,BX,BY,BN);
b8=hbb(X+35,Y,b8,BX,BY,BN);
b9=hbb(X+40,Y,b9,BX,BY,BN);
b10=hbb(X+45,Y,b10,BX,BY,BN);
b11=hbb(X+50,Y,b11,BX,BY,BN);
b12=hbb(X+55,Y,b12,BX,BY,BN);
b13=hbb(X+60,Y,b13,BX,BY,BN);
b14=hbb(X+65,Y,b14,BX,BY,BN);
b15=hbb(X+70,Y,b15,BX,BY,BN);
b16=hbb(X+75,Y,b16,BX,BY,BN);
b17=hbb(X+80,Y,b17,BX,BY,BN);
b18=hbb(X+85,Y,b18,BX,BY,BN);
b19=hbb(X+90,Y,b19,BX,BY,BN);
b20=hbb(X+95,Y,b20,BX,BY,BN);



if(w==1){a11=b1;a12=b2;a13=b3;a14=b4;a15=b5;a16=b6;a17=b7;a18=b8;a19=b9;a110=b10;a111=b11;a112=b12;a113=b13;a114=b14;a115=b15;a116=b16;a117=b17;a118=b18;a119=b19;a120=b20;}
if(w==2){a21=b1;a22=b2;a23=b3;a24=b4;a25=b5;a26=b6;a27=b7;a28=b8;a29=b9;a210=b10;a211=b11;a212=b12;a213=b13;a214=b14;a215=b15;a216=b16;a217=b17;a218=b18;a219=b19;a220=b20;}
if(w==3){a31=b1;a32=b2;a33=b3;a34=b4;a35=b5;a36=b6;a37=b7;a38=b8;a39=b9;a310=b10;a311=b11;a312=b12;a313=b13;a314=b14;a315=b15;a316=b16;a317=b17;a318=b18;a319=b19;a320=b20;}
if(w==4){a41=b1;a42=b2;a43=b3;a44=b4;a45=b5;a46=b6;a47=b7;a48=b8;a49=b9;a410=b10;a411=b11;a412=b12;a413=b13;a414=b14;a415=b15;a416=b16;a417=b17;a418=b18;a419=b19;a420=b20;}
if(w==5){a51=b1;a52=b2;a53=b3;a54=b4;a55=b5;a56=b6;a57=b7;a58=b8;a59=b9;a510=b10;a511=b11;a512=b12;a513=b13;a514=b14;a515=b15;a516=b16;a517=b17;a518=b18;a519=b19;a520=b20;}
if(w==6){a61=b1;a62=b2;a63=b3;a64=b4;a65=b5;a66=b6;a67=b7;a68=b8;a69=b9;a610=b10;a611=b11;a612=b12;a613=b13;a614=b14;a615=b15;a616=b16;a617=b17;a618=b18;a619=b19;a620=b20;}
if(w==7){a71=b1;a72=b2;a73=b3;a74=b4;a75=b5;a76=b6;a77=b7;a78=b8;a79=b9;a710=b10;a711=b11;a712=b12;a713=b13;a714=b14;a715=b15;a716=b16;a717=b17;a718=b18;a719=b19;a720=b20;}
if(w==8){a81=b1;a82=b2;a83=b3;a84=b4;a85=b5;a86=b6;a87=b7;a88=b8;a89=b9;a810=b10;a811=b11;a812=b12;a813=b13;a814=b14;a815=b15;a816=b16;a817=b17;a818=b18;a819=b19;a820=b20;}
if(w==9){a91=b1;a92=b2;a93=b3;a94=b4;a95=b5;a96=b6;a97=b7;a98=b8;a99=b9;a910=b10;a911=b11;a912=b12;a913=b13;a914=b14;a915=b15;a916=b16;a917=b17;a918=b18;a919=b19;a920=b20;}
if(w==10){a101=b1;a102=b2;a103=b3;a104=b4;a105=b5;a106=b6;a107=b7;a108=b8;a109=b9;a1010=b10;a1011=b11;a1012=b12;a1013=b13;a1014=b14;a1015=b15;a1016=b16;a1017=b17;a1018=b18;a1019=b19;a1020=b20;}
if(w==11){a111b=b1;a112b=b2;a113b=b3;a114b=b4;a115b=b5;a116b=b6;a117b=b7;a118b=b8;a119b=b9;a1110=b10;a1111=b11;a1112=b12;a1113=b13;a1114=b14;a1115=b15;a1116=b16;a1117=b17;a1118=b18;a1119=b19;a1120=b20;}

}



bool htb(float X,float Y,int bX,int bY,bool b1){
    if(b1==true){
   if(X<=bX+4.9&&X>=bX-3.9&&Y<=bY+4.9&&Y>=bY-3.9){
   return true;
}else{return false;}
}else{return false;}
}
//if(X>=bX){TX=TX+1;}else{TX=TX-1;}if(Y>=bY){TY=TY+1;}else{TY=TY-1;}

bool tb(float X,float Y,int bX,int bY,bool b1,bool b2,bool b3,bool b4,bool b5,bool b6,bool b7,bool b8,bool b9,bool b10,
bool b11,bool b12,bool b13,bool b14,bool b15,bool b16,bool b17,bool b18,bool b19,bool b20){

 if (htb(X,Y,bX,bY,b1)==true||
  htb(X,Y,bX+5,bY,b2)==true||
  htb(X,Y,bX+10,bY,b3)==true||
  htb(X,Y,bX+15,bY,b4)==true||
  htb(X,Y,bX+20,bY,b5)==true||
  htb(X,Y,bX+25,bY,b6)==true||
  htb(X,Y,bX+30,bY,b7)==true||
  htb(X,Y,bX+35,bY,b8)==true||
  htb(X,Y,bX+40,bY,b9)==true||
  htb(X,Y,bX+45,bY,b10)==true||
  htb(X,Y,bX+50,bY,b11)==true||
  htb(X,Y,bX+55,bY,b12)==true||
  htb(X,Y,bX+60,bY,b13)==true||
  htb(X,Y,bX+65,bY,b14)==true||
  htb(X,Y,bX+70,bY,b15)==true||
  htb(X,Y,bX+75,bY,b16)==true||
  htb(X,Y,bX+80,bY,b17)==true||
  htb(X,Y,bX+85,bY,b18)==true||
  htb(X,Y,bX+90,bY,b19)==true||
  htb(X,Y,bX+95,bY,b20)==true){return true;}
  else{return false;}




}











task rlT(){
  while(1==1){
  rl=0;
  if(nNxtButtonPressed==1){rl=1;}
    if(nNxtButtonPressed==2){rl=2;}
    wait1Msec(10);
  }
}















task main(){

nxtDisplayCenteredTextLine(2,"bombermanNXT");

wait1Msec(1000);

StartTask(rlT);

while(1==1){

  c1turn=false;
  c2turn=false;
  c3turn=false;


  eraseDisplay();

 nxtDrawEllipse(X+2,Y+2,X-2,Y-2);
  if(dir==0){nxtDrawLine(X,Y,X,Y+3);}
    if(dir==1){nxtDrawLine(X,Y,X+3,Y);}
      if(dir==2){nxtDrawLine(X,Y,X,Y-3);}
        if(dir==3){nxtDrawLine(X,Y,X-3,Y);}

        if(BN>=0){nxtFillEllipse(BX+2,BY+2,BX-2,BY-2);}

        if(BN<=50&&BN>=0){nxtFillRect(BX-2,BY+7,BX+2,BY-7);nxtFillRect(BX-7,BY+2,BX+7,BY-2);
        if(X<=BX+9&&X>=BX-9&&Y<=BY+4&&Y>=BY-4||X<=BX+4&&X>=BX-4&&Y<=BY+9&&Y>=BY-9){Y=1000;}
        if(c1X<=BX+9&&c1X>=BX-9&&c1Y<=BY+4&&c1Y>=BY-4||c1X<=BX+4&&c1X>=BX-4&&c1Y<=BY+9&&c1Y>=BY-9){c1Y=1000;}
        if(c2X<=BX+9&&c2X>=BX-9&&c2Y<=BY+4&&c2Y>=BY-4||c2X<=BX+4&&c2X>=BX-4&&c2Y<=BY+9&&c2Y>=BY-9){c2Y=1000;}
        if(c3X<=BX+9&&c3X>=BX-9&&c3Y<=BY+4&&c3Y>=BY-4||c3X<=BX+4&&c3X>=BX-4&&c3Y<=BY+9&&c3Y>=BY-9){c3Y=1000;}}


 nxtDrawEllipse(c1X+2,c1Y+2,c1X-2,c1Y-2);
  if(c1dir==0){nxtDrawLine(c1X,c1Y,c1X,c1Y+3);}
    if(c1dir==1){nxtDrawLine(c1X,c1Y,c1X+3,c1Y);}
      if(c1dir==2){nxtDrawLine(c1X,c1Y,c1X,c1Y-3);}
        if(c1dir==3){nxtDrawLine(c1X,c1Y,c1X-3,c1Y);}


        if(c1BN>=0){nxtFillEllipse(c1BX+2,c1BY+2,c1BX-2,c1BY-2);}

        if(c1BN<=50&&c1BN>=0){nxtFillRect(c1BX-2,c1BY+7,c1BX+2,c1BY-7);nxtFillRect(c1BX-7,c1BY+2,c1BX+7,c1BY-2);
        if(c1X<=c1BX+9&&c1X>=c1BX-9&&c1Y<=c1BY+4&&c1Y>=c1BY-4||c1X<=c1BX+4&&c1X>=c1BX-4&&c1Y<=c1BY+9&&c1Y>=c1BY-9){c1Y=1000;}
        if(c2X<=c1BX+9&&c2X>=c1BX-9&&c2Y<=c1BY+4&&c2Y>=c1BY-4||c2X<=c1BX+4&&c2X>=c1BX-4&&c2Y<=c1BY+9&&c2Y>=c1BY-9){c2Y=1000;}
        if(c3X<=c1BX+9&&c3X>=c1BX-9&&c3Y<=c1BY+4&&c3Y>=c1BY-4||c3X<=c1BX+4&&c3X>=c1BX-4&&c3Y<=c1BY+9&&c3Y>=c1BY-9){c3Y=1000;}
        if(X<=c1BX+9&&X>=c1BX-9&&Y<=c1BY+4&&Y>=c1BY-4||X<=c1BX+4&&X>=c1BX-4&&Y<=c1BY+9&&Y>=c1BY-9){Y=1000;}}


 nxtDrawEllipse(c2X+2,c2Y+2,c2X-2,c2Y-2);
  if(c2dir==0){nxtDrawLine(c2X,c2Y,c2X,c2Y+3);}
    if(c2dir==1){nxtDrawLine(c2X,c2Y,c2X+3,c2Y);}
      if(c2dir==2){nxtDrawLine(c2X,c2Y,c2X,c2Y-3);}
        if(c2dir==3){nxtDrawLine(c2X,c2Y,c2X-3,c2Y);}


        if(c2BN>=0){nxtFillEllipse(c2BX+2,c2BY+2,c2BX-2,c2BY-2);}

        if(c2BN<=50&&c2BN>=0){nxtFillRect(c2BX-2,c2BY+7,c2BX+2,c2BY-7);nxtFillRect(c2BX-7,c2BY+2,c2BX+7,c2BY-2);
        if(c2X<=c2BX+9&&c2X>=c2BX-9&&c2Y<=c2BY+4&&c2Y>=c2BY-4||c2X<=c2BX+4&&c2X>=c2BX-4&&c2Y<=c2BY+9&&c2Y>=c2BY-9){c2Y=1000;}
        if(c1X<=c2BX+9&&c1X>=c2BX-9&&c1Y<=c2BY+4&&c1Y>=c2BY-4||c1X<=c2BX+4&&c1X>=c2BX-4&&c1Y<=c2BY+9&&c1Y>=c2BY-9){c1Y=1000;}
        if(c3X<=c2BX+9&&c3X>=c2BX-9&&c3Y<=c2BY+4&&c3Y>=c2BY-4||c3X<=c2BX+4&&c3X>=c2BX-4&&c3Y<=c2BY+9&&c3Y>=c2BY-9){c3Y=1000;}
        if(X<=c2BX+9&&X>=c2BX-9&&Y<=c2BY+4&&Y>=c2BY-4||X<=c2BX+4&&X>=c2BX-4&&Y<=c2BY+9&&Y>=c2BY-9){Y=1000;}}


        nxtDrawEllipse(c3X+2,c3Y+2,c3X-2,c3Y-2);
  if(c3dir==0){nxtDrawLine(c3X,c3Y,c3X,c3Y+3);}
    if(c3dir==1){nxtDrawLine(c3X,c3Y,c3X+3,c3Y);}
      if(c3dir==2){nxtDrawLine(c3X,c3Y,c3X,c3Y-3);}
        if(c3dir==3){nxtDrawLine(c3X,c3Y,c3X-3,c3Y);}


        if(c3BN>=0){nxtFillEllipse(c3BX+2,c3BY+2,c3BX-2,c3BY-2);}

        if(c3BN<=50&&c3BN>=0){nxtFillRect(c3BX-2,c3BY+7,c3BX+2,c3BY-7);nxtFillRect(c3BX-7,c3BY+2,c3BX+7,c3BY-2);
        if(c3X<=c3BX+9&&c3X>=c3BX-9&&c3Y<=c3BY+4&&c3Y>=c3BY-4||c3X<=c3BX+4&&c3X>=c3BX-4&&c3Y<=c3BY+9&&c3Y>=c3BY-9){c3Y=1000;}
        if(c1X<=c3BX+9&&c1X>=c3BX-9&&c1Y<=c3BY+4&&c1Y>=c3BY-4||c1X<=c3BX+4&&c1X>=c3BX-4&&c1Y<=c3BY+9&&c1Y>=c3BY-9){c1Y=1000;}
        if(c2X<=c3BX+9&&c2X>=c3BX-9&&c2Y<=c3BY+4&&c2Y>=c3BY-4||c2X<=c3BX+4&&c2X>=c3BX-4&&c2Y<=c3BY+9&&c2Y>=c3BY-9){c3Y=1000;}
        if(X<=c3BX+9&&X>=c3BX-9&&Y<=c3BY+4&&Y>=c3BY-4||X<=c3BX+4&&X>=c3BX-4&&Y<=c3BY+9&&Y>=c3BY-9){Y=1000;}}


nxtDisplayTextLine(0,"time %d",1000-turn);
nxtDrawLine(0,55,100,55);
nxtFillRect(0,-1,100,killer);

if(turn>=900){nxtDisplayStringAt(45,63,"hurry up!");}
if(turn>=1001){turn=1000;}


c1R=c1T=c1B=c1L=false;
c2R=c2T=c2B=c2L=false;
c3R=c3T=c3B=c3L=false;

        drawblocks(2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120);
  drawblocks(2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220);
drawblocks(2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320);
drawblocks(2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420);
drawblocks(2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520);
drawblocks(2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620);
drawblocks(2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720);
drawblocks(2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820);
drawblocks(2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920);
drawblocks(2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020);
drawblocks(2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120);




if(BN>=0&&BN<=50){
bBlock(2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120,BX,BY,BN,1);
bBlock(2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220,BX,BY,BN,2);
bBlock(2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320,BX,BY,BN,3);
bBlock(2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420,BX,BY,BN,4);
bBlock(2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520,BX,BY,BN,5);
bBlock(2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620,BX,BY,BN,6);
bBlock(2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720,BX,BY,BN,7);
bBlock(2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820,BX,BY,BN,8);
bBlock(2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920,BX,BY,BN,9);
bBlock(2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020,BX,BY,BN,10);
bBlock(2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120,BX,BY,BN,11);
}

if(c1BN>=0&&c1BN<=50){
bBlock(2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120,c1BX,c1BY,c1BN,1);
bBlock(2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220,c1BX,c1BY,c1BN,2);
bBlock(2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320,c1BX,c1BY,c1BN,3);
bBlock(2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420,c1BX,c1BY,c1BN,4);
bBlock(2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520,c1BX,c1BY,c1BN,5);
bBlock(2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620,c1BX,c1BY,c1BN,6);
bBlock(2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720,c1BX,c1BY,c1BN,7);
bBlock(2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820,c1BX,c1BY,c1BN,8);
bBlock(2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920,c1BX,c1BY,c1BN,9);
bBlock(2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020,c1BX,c1BY,c1BN,10);
bBlock(2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120,c1BX,c1BY,c1BN,11);
}


if(c2BN>=0&&c2BN<=50){
bBlock(2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120,c2BX,c2BY,c2BN,1);
bBlock(2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220,c2BX,c2BY,c2BN,2);
bBlock(2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320,c2BX,c2BY,c2BN,3);
bBlock(2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420,c2BX,c2BY,c2BN,4);
bBlock(2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520,c2BX,c2BY,c2BN,5);
bBlock(2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620,c2BX,c2BY,c2BN,6);
bBlock(2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720,c2BX,c2BY,c2BN,7);
bBlock(2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820,c2BX,c2BY,c2BN,8);
bBlock(2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920,c2BX,c2BY,c2BN,9);
bBlock(2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020,c2BX,c2BY,c2BN,10);
bBlock(2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120,c2BX,c2BY,c2BN,11);
}

if(c3BN>=0&&c3BN<=50){
bBlock(2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120,c3BX,c3BY,c3BN,1);
bBlock(2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220,c3BX,c3BY,c3BN,2);
bBlock(2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320,c3BX,c3BY,c3BN,3);
bBlock(2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420,c3BX,c3BY,c3BN,4);
bBlock(2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520,c3BX,c3BY,c3BN,5);
bBlock(2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620,c3BX,c3BY,c3BN,6);
bBlock(2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720,c3BX,c3BY,c3BN,7);
bBlock(2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820,c3BX,c3BY,c3BN,8);
bBlock(2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920,c3BX,c3BY,c3BN,9);
bBlock(2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020,c3BX,c3BY,c3BN,10);
bBlock(2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120,c3BX,c3BY,c3BN,11);
}







if(nNxtButtonPressed==3){if(dir==0){Y=Y+1;}if(dir==1){X=X+1;}if(dir==2){Y=Y-1;}if(dir==3){X=X-1;}
while(tb(X,Y,2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120)==true||
tb(X,Y,2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220)==true||
tb(X,Y,2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320)==true||
tb(X,Y,2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420)==true||
tb(X,Y,2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520)==true||
tb(X,Y,2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620)==true||
tb(X,Y,2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720)==true||
tb(X,Y,2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820)==true||
tb(X,Y,2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920)==true||
tb(X,Y,2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020)==true||
tb(X,Y,2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120)==true)

{

  if(dir==0){Y=Y-0.5;}if(dir==1){X=X-0.5;}if(dir==2){Y=Y+0.5;}if(dir==3){X=X+0.5;}
}
}

if(rl==1||nNxtButtonPressed==1){if(R==false){if(dir<=2){dir=dir+1;}else{dir=0;}R=true;}}else{R=false;}
         if(rl==2||nNxtButtonPressed==2){if(L==false){if(dir>=1){dir=dir-1;}else{dir=3;}L=true;}}else{L=false;}

        if(SensorValue(S1)==1&&BN<=0){BX=X;BY=Y;BN=800;}


if(c1mve==true){if(c1dir==0){c1Y=c1Y+1;}if(c1dir==1){c1X=c1X+1;}if(c1dir==2){c1Y=c1Y-1;}if(c1dir==3){c1X=c1X-1;}
while(tb(c1X,c1Y,2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220)==true||
tb(c1X,c1Y,2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320)==true||
tb(c1X,c1Y,2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420)==true||
tb(c1X,c1Y,2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520)==true||
tb(c1X,c1Y,2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620)==true||
tb(c1X,c1Y,2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720)==true||
tb(c1X,c1Y,2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820)==true||
tb(c1X,c1Y,2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920)==true||
tb(c1X,c1Y,2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020)==true||
tb(c1X,c1Y,2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120)==true)

{
c1turn=true;
  if(c1dir==0){c1Y=c1Y-0.5;}if(c1dir==1){c1X=c1X-0.5;}if(c1dir==2){c1Y=c1Y+0.5;}if(c1dir==3){c1X=c1X+0.5;}
}
}


if(c2mve==true){if(c2dir==0){c2Y=c2Y+1;}if(c2dir==1){c2X=c2X+1;}if(c2dir==2){c2Y=c2Y-1;}if(c2dir==3){c2X=c2X-1;}
while(tb(c2X,c2Y,2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120)==true||
tb(c2X,c2Y,2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220)==true||
tb(c2X,c2Y,2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320)==true||
tb(c2X,c2Y,2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420)==true||
tb(c2X,c2Y,2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520)==true||
tb(c2X,c2Y,2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620)==true||
tb(c2X,c2Y,2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720)==true||
tb(c2X,c2Y,2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820)==true||
tb(c2X,c2Y,2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920)==true||
tb(c2X,c2Y,2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020)==true||
tb(c2X,c2Y,2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120)==true)

{
c2turn=true;
  if(c2dir==0){c2Y=c2Y-0.5;}if(c2dir==1){c2X=c2X-0.5;}if(c2dir==2){c2Y=c2Y+0.5;}if(c2dir==3){c2X=c2X+0.5;}
}
}

if(c3mve==true){if(c3dir==0){c3Y=c3Y+1;}if(c3dir==1){c3X=c3X+1;}if(c3dir==2){c3Y=c3Y-1;}if(c3dir==3){c3X=c3X-1;}
while(tb(c3X,c3Y,2,2,a11,a12,a13,a14,a15,a16,a17,a18,a19,a110,a111,a112,a113,a114,a115,a116,a117,a118,a119,a120)==true||
tb(c3X,c3Y,2,7,a21,a22,a23,a24,a25,a26,a27,a28,a29,a210,a211,a212,a213,a214,a215,a216,a217,a218,a219,a220)==true||
tb(c3X,c3Y,2,12,a31,a32,a33,a34,a35,a36,a37,a38,a39,a310,a311,a312,a313,a314,a315,a316,a317,a318,a319,a320)==true||
tb(c3X,c3Y,2,17,a41,a42,a43,a44,a45,a46,a47,a48,a49,a410,a411,a412,a413,a414,a415,a416,a417,a418,a419,a420)==true||
tb(c3X,c3Y,2,22,a51,a52,a53,a54,a55,a56,a57,a58,a59,a510,a511,a512,a513,a514,a515,a516,a517,a518,a519,a520)==true||
tb(c3X,c3Y,2,27,a61,a62,a63,a64,a65,a66,a67,a68,a69,a610,a611,a612,a613,a614,a615,a616,a617,a618,a619,a620)==true||
tb(c3X,c3Y,2,32,a71,a72,a73,a74,a75,a76,a77,a78,a79,a710,a711,a712,a713,a714,a715,a716,a717,a718,a719,a720)==true||
tb(c3X,c3Y,2,37,a81,a82,a83,a84,a85,a86,a87,a88,a89,a810,a811,a812,a813,a814,a815,a816,a817,a818,a819,a820)==true||
tb(c3X,c3Y,2,42,a91,a92,a93,a94,a95,a96,a97,a98,a99,a910,a911,a912,a913,a914,a915,a916,a917,a918,a919,a920)==true||
tb(c3X,c3Y,2,47,a101,a102,a103,a104,a105,a106,a107,a108,a109,a1010,a1011,a1012,a1013,a1014,a1015,a1016,a1017,a1018,a1019,a1020)==true||
tb(c3X,c3Y,2,52,a111b,a112b,a113b,a114b,a115b,a116b,a117b,a118b,a119b,a1110,a1111,a1112,a1113,a1114,a1115,a1116,a1117,a1118,a1119,a1120)==true)

{
c3turn=true;
  if(c3dir==0){c3Y=c3Y-1.7;}if(c3dir==1){c3X=c3X-1.7;}if(c3dir==2){c3Y=c3Y+1.7;}if(c3dir==3){c3X=c3X+1.7;}
}
}




if(X<=1){X=X+1;}
if(X>=99){X=X-1;}
if(Y<=1){Y=Y+1;}
if(Y>=53){Y=Y-1;}

if(c1X<=1){c1X=c1X+1;c1turn=true;}
if(c1X>=99){c1X=c1X-1;c1turn=true;}
if(c1Y<=1){c1Y=c1Y+1;c1turn=true;}
if(c1Y>=53){c1Y=c1Y-1;c1turn=true;}

if(c1Y>=55){c1T=true;}

if(c2X<=1){c2X=c2X+1;c2turn=true;}
if(c2X>=99){c2X=c2X-1;c2turn=true;}
if(c2Y<=1){c2Y=c2Y+1;c2turn=true;}
if(c2Y>=53){c2Y=c2Y-1;c2turn=true;}

if(c2Y>=55){c2T=true;}

if(c3X<=1){c3X=c3X+1;c3turn=true;}
if(c3X>=99){c3X=c3X-1;c3turn=true;}
if(c3Y<=1){c3Y=c3Y+1;c3turn=true;}
if(c3Y>=53){c3Y=c3Y-1;c3turn=true;}

if(c3Y>=55){c3T=true;}

turn=turn+1;


if(rl==1||nNxtButtonPressed==1){if(R==false){if(dir<=2){dir=dir+1;}else{dir=0;}R=true;}}else{R=false;}
         if(rl==2||nNxtButtonPressed==2){if(L==false){if(dir>=1){dir=dir-1;}else{dir=3;}L=true;}}else{L=false;}

        if(SensorValue(S1)==1&&BN<=0){BX=X;BY=Y;BN=800;}


if(c1Y<=70){

c1mve=false;
if(turn<=90&&c1X<=10&&c1Y>=50){c1dir=2;}
if(turn<=30){if(c1Y<=52){c1dir=0;}else{c1dir=1;}c1mve=true;}
if(c1BN<=-30){c1mve=true;}
if(c1X<=c1BX+9&&c1X>=c1BX-9&&c1Y<=c1BY+4&&c1Y>=c1BY-4||c1X<=c1BX+4&&c1X>=c1BX-4&&c1Y<=c1BY+9&&c1Y>=c1BY-9){c1mve=true;}
if(c1X<=c2BX+9&&c1X>=c2BX-9&&c1Y<=c2BY+4&&c1Y>=c2BY-4||c1X<=c2BX+4&&c1X>=c2BX-4&&c1Y<=c2BY+9&&c1Y>=c2BY-9&&c2BN>=0){c1mve=true;}
if(c1X<=c3BX+9&&c1X>=c3BX-9&&c1Y<=c3BY+4&&c1Y>=c3BY-4||c1X<=c3BX+4&&c1X>=c3BX-4&&c1Y<=c3BY+9&&c1Y>=c3BY-9&&c3BN>=0){c1mve=true;}
if(c1X<=BX+9&&c1X>=BX-9&&c1Y<=BY+4&&c1Y>=BY-4||c1X<=BX+4&&c1X>=BX-4&&c1Y<=BY+9&&c1Y>=BY-9&&BN>=0){c1mve=true;}

if(c1BN<=0){if(c1T==true||c1B==true||c1L==true||c1R==true){c1BX=c1X;c1BY=c1Y;c1BN=800;}}
//if(c1R==true){if(c1T==true){if(c1B==true){c1dir=3;}else{c1dir=2;}}else{c1dir=0;}}/////////////////////////////////////////////////////
//if(c1T==true){if(c1L==true){if(c1R==true){c1dir=2;}else{c1dir=1;}}else{c1dir=3;}}
//if(c1L==true){if(c1B==true){if(c1T==true){c1dir=1;}else{c1dir=0;}}else{c1dir=2;}}
//if(c1B==true){if(c1R==true){if(c1L==true){c1dir=0;}else{c1dir=3;}}else{c1dir=1;}}
  //if(c1dir==0&&c1T==true){if(random(100)>=50){dir=3;}else{dir=1;}}
  //if(c1dir==1&&c1R==true){if(random(100)>=50){dir=0;}else{dir=2;}}
  //if(c1dir==2&&c1B==true){if(random(100)>=50){dir=1;}else{dir=3;}}
  //if(c1dir==3&&c1L==true){if(random(100)>=50){dir=2;}else{dir=0;}}

if(turn>=1000){c1dir=0;}
//if(c1R==true){if(c1T==true){if(c1B==true){c1dir=3;}else{c1dir=2;}}else{c1dir=0;}}/////////////////////////////////////////////////////
//if(c1T==true){if(c1L==true){if(c1R==true){c1dir=2;}else{c1dir=1;}}else{c1dir=3;}}
//if(c1L==true){if(c1B==true){if(c1T==true){c1dir=1;}else{c1dir=0;}}else{c1dir=2;}}
//if(c1B==true){if(c1R==true){if(c1L==true){c1dir=0;}else{c1dir=3;}}else{c1dir=1;}}

//if(c1dir==0&&c1T==true){if(random(100)>=50){c1dir=3;}else{c1dir=1;}}
  //if(c1dir==1&&c1R==true){if(random(100)>=50){c1dir=0;}else{c1dir=2;}}
  //if(c1dir==2&&c1B==true){if(random(100)>=50){c1dir=1;}else{c1dir=3;}}
  //if(c1dir==3&&c1L==true){if(random(100)>=50){c1dir=2;}else{c1dir=0;}}

//if(c1dir==0&&c1T==true){c1dir=random(3);}
//if(c1dir==1&&c1R==true){c1dir=random(3);}
//if(c1dir==2&&c1B==true){c1dir=random(3);}
//if(c1dir==3&&c1L==true){c1dir=random(3);}

XD1=c1dir;
if(c1turn==true){c1dir=random(3);if(c1dir==XD1-2||c1dir==XD1+2||c1dir==XD1){c1dir=random(3);}}

if(turn<=30){if(c1Y<=51){c1dir=0;}else{c1dir=1;}}

}//end of if(c1Y<=70){

if(c2Y<=70){

c2mve=false;

if(turn<=70&&c2X>=90&&c2Y>=50){c2dir=2;}
if(c2X<=c2BX+9&&c2X>=c2BX-9&&c2Y<=c2BY+4&&c2Y>=c2BY-4||c2X<=c2BX+4&&c2X>=c2BX-4&&c2Y<=c2BY+9&&c2Y>=c2BY-9){c2mve=true;}
if(c2BN<=-30){c2mve=true;}
if(turn<=30){if(c2Y<=51){c2dir=0;}else{c2dir=3;}c2mve=true;}
if(c2X<=BX+9&&c2X>=BX-9&&c2Y<=BY+4&&c2Y>=BY-4||c2X<=BX+4&&c2X>=BX-4&&c2Y<=BY+9&&c2Y>=BY-9&&BN>=0){c2mve=true;}
if(c2X<=c1BX+9&&c2X>=c1BX-9&&c2Y<=c1BY+4&&c2Y>=c1BY-4||c2X<=c1BX+4&&c2X>=c1BX-4&&c2Y<=c1BY+9&&c2Y>=c1BY-9&&c1BN>=0){c2mve=true;}
if(c2X<=c3BX+9&&c2X>=c3BX-9&&c2Y<=c3BY+4&&c2Y>=c3BY-4||c2X<=c3BX+4&&c2X>=c3BX-4&&c2Y<=c3BY+9&&c2Y>=c3BY-9&&c3BN>=0){c2mve=true;}

if(c2BN<=0){if(c2T==true||c2B==true||c2L==true||c2R==true){c2BX=c2X;c2BY=c2Y;c2BN=800;}}


if(turn>=1000){c2dir=0;}


XD2=c2dir;
if(c2turn==true){c2dir=random(3);if(c2dir==XD2-2||c2dir==XD2+2||c2dir==XD2){c2dir=random(3);}}

if(turn<=30){if(c2Y<=51){c2dir=0;}else{c2dir=3;}}

}//end of if(c2Y<=70){


if(c3Y<=70){


c3mve=false;

if(turn<=70&&c3X>=95&&c3Y<=10){c3dir=0;}
if(c3X<=c3BX+9&&c3X>=c3BX-9&&c3Y<=c3BY+4&&c3Y>=c3BY-4||c3X<=c3BX+4&&c3X>=c3BX-4&&c3Y<=c3BY+9&&c3Y>=c3BY-9){c3mve=true;}
if(c3BN<=-30){c3mve=true;}
if(turn<=30){if(c3Y>=3){c3dir=2;}else{c3dir=3;}}
if(c3X<=BX+9&&c3X>=BX-9&&c3Y<=BY+4&&c3Y>=BY-4||c3X<=BX+4&&c3X>=BX-4&&c3Y<=BY+9&&c3Y>=BY-9){c3mve=true;}
if(c3X<=c1BX+9&&c3X>=c1BX-9&&c3Y<=c1BY+4&&c3Y>=c1BY-4||c3X<=c1BX+4&&c3X>=c1BX-4&&c3Y<=c1BY+9&&c3Y>=c1BY-9){c3mve=true;}
if(c3X<=c2BX+9&&c3X>=c2BX-9&&c3Y<=c2BY+4&&c3Y>=c2BY-4||c3X<=c2BX+4&&c3X>=c2BX-4&&c3Y<=c2BY+9&&c3Y>=c2BY-9){c3mve=true;}

if(c3BN<=0){if(c3T==true||c3B==true||c3L==true||c3R==true){c3BX=c3X;c3BY=c3Y;c3BN=800;}}


if(turn>=1000){c3dir=0;}


XD3=c3dir;
if(c3turn==true){c3dir=random(3);if(c3dir==XD3-2||c3dir==XD3+2||c3dir==XD3){c3dir=random(3);}}


}//end of if(c3Y<=70){



if(turn==5){Y=7;}



if(c1Y>=70&&c2Y>=70&&c3Y>=70&&Y<=70){eraseDisplay();nxtDisplayBigTextLine(3,"You Win!");wait1Msec(10000);}
if(Y>=70){eraseDisplay();nxtDisplayBigTextLine(3,"You LOSE!");wait1Msec(10000);}


killer=killer+1;


if(Y<=killer){Y=1000;}
if(c1Y<=killer){c1Y=1000;}
if(c2Y<=killer){c2Y=1000;}
if(c3Y<=killer){c3Y=1000;}

  BN=BN-20;
  c1BN=c1BN-20;
  c2BN=c2BN-20;
  c3BN=c3BN-20;



        if(rl==1||nNxtButtonPressed==1){if(R==false){if(dir<=2){dir=dir+1;}else{dir=0;}R=true;}}else{R=false;}
         if(rl==2||nNxtButtonPressed==2){if(L==false){if(dir>=1){dir=dir-1;}else{dir=3;}L=true;}}else{L=false;}

        if(SensorValue(S1)==1&&BN<=0){BX=X;BY=Y;BN=800;}


wait1Msec(1);
}


}
