#pragma config(Sensor, S1,     T,                   sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int mun=50;int CCC;int GW;int SW;int BW;int MWE;int RWE;int BWE;int SP;int AP;int TP;int STP;bool PB;int WSN;//mun=money  , CCC=selecting arrow X , GW=Golden wagon , SW=silver wagon , BW=bronze wagon , MWE=mines weapon , RWE=rockets weapon , BWE=boost weapon , SP=speed perk , AP=acceleration perk , TP=toughness perk , STP=steering perk , PB=perk something , WSN=wagon stat number
float X=50;float Y=-50;int DN;float YJ=0.02;float XJ=0.02;float sYJ=0.02;float sXJ=0.02;float aiti;int AX;float AY;float DXJ;float DYJ;float SDXJ;float SDYJ;float t1X;float t1Y;float t2X;float t2Y;//X=player X , Y=player Y , DN=display number , YJ=player YJ , XJ=player XJ , aiti=airtime , AX=absolute X , AY=absolute Y , DJX=display XJ , DJY=display YJ , T1x=tree 1 X , T1y=tree 1 Y , T2x=tree 2 X , T2y=tree 2 Y
float spd;int Ispd;float CB1X;float CB1Y;float w1x1;float w1y1;float w1x2;float w1y2;float w1cx;float w1cy;int tme;int Dtme;//spd=speed , Ispd=displayed speed , CB1X=collectable boost 1 X , CB1Y=collectable boost 1 Y , w1x1=wall 1 X 1 , w1y1=wall 1 Y 1 , w1x2=wall 1 X 2 , w1y2=wall 1 Y 2 , w1cx=wall 1 creation X , w1cy=wall 1 creation Y , tme=time , Dtme=display time
float dot1x;float dot1y;float dot1xj;float dot1yj;bool ddot1;float dot2x;float dot2y;float dot2xj;float dot2yj;bool ddot2;float dot3x;float dot3y;float dot3xj;float dot3yj;bool ddot3;float dot4x;float dot4y;float dot4xj;float dot4yj;float ex1x;float ex1y;int ex1n;float jp1x;float jp1y;
float RT;int DRT;float RCT1x;float RCT1y;float RCT1XJ;float RCT1YJ;float RCT1DXJ;float RCT1DYJ;int MT;int DMT;float MX;float MY;//RT=reload time , DRT=display reload time , RCT1x=rocket 1 X , RCT1y=rocket 1 Y , RCT1XJ=rocket 1 XJ ,  RCT1YJ=rocket 1 YJ , RCT1DXJ=rocket 1 display XJ , RCT1DYJ=rocket 1 display YJ

task main(){float gx;float gy=4;float gj;bool cont;bool gst;int rdng;int read;int arrow;

  while(cont==false){
  eraseDisplay();



  nxtDrawLine(gx-2,gy,gx,gy+2);
  nxtDrawLine(gx+2,gy,gx,gy+2);
nxtDrawLine(gx,gy+6,gx,gy+2);
nxtDrawLine(gx-2,gy+5,gx+2,gy+5);
nxtDrawRect(gx-1,gy+6,gx+1,gy+8);

nxtDrawRect(10,1,90,50);
nxtDrawRect(20,1,30,20);
nxtDrawRect(27,10,28,11);
nxtDrawRect(-10,1,110,2);

nxtDrawRect(40,10,50,20);
nxtDrawRect(40,10,45,15);
nxtDrawRect(45,15,50,20);

nxtDrawRect(55,10,60,6);

arrow=arrow-1;

if(arrow<=-80){arrow=80;}

if(read==0){if(arrow>=0){nxtDrawLine(57,25,57,15);nxtDrawLine(57,15,60,20);nxtDrawLine(57,15,54,20);}}

if(read==1){if(arrow>=0){nxtDrawLine(68,25,68,15);nxtDrawLine(68,15,71,20);nxtDrawLine(68,15,65,20);}}

if(read==2){if(arrow>=0){nxtDrawLine(26,35,26,25);nxtDrawLine(26,25,29,30);nxtDrawLine(26,25,23,30);}}


if(read<=1){nxtDrawLine(20,1,30,20);nxtDrawLine(30,1,20,20);}

if(read>=1){nxtDrawRect(70,10,65,6);}

gy=gy+gj;

gst=false;
if(gy<=3.4){gst=true;}
if(gst==true){gj=0;}
else{gj=gj-0.01;}




if(nNxtButtonPressed==1){gx=gx+0.25;}
if(nNxtButtonPressed==2){gx=gx-0.25;}
rdng=0;
if(nNxtButtonPressed==3){if(gx<=35){if(gx>=15){if(gy<=20){if(read>=2){cont=true;}}}}if(gx<=63.5){if(gx>=52.5){if(gy<=15){rdng=1;}}}if(gx<=73.5){if(gx>=62.5){if(gy<=15){if(read>=1){rdng=2;}}}}if(rdng<=0){if(gst==true){gj=0.5;}}}
wait1Msec(5);

if(rdng==1){eraseDisplay();
  nxtDisplayCenteredTextLine(1,"Independence!");
nxtDisplayCenteredTextLine(3,"You are free");
nxtDisplayCenteredTextLine(4,"to go to");
nxtDisplayCenteredTextLine(5,"Oregon.");
wait1Msec(1000);
while(nNxtButtonPressed<=2){eraseDisplay();
nxtDisplayCenteredTextLine(1,"Independence!");
nxtDisplayCenteredTextLine(3,"You are free");
nxtDisplayCenteredTextLine(4,"to go to");
nxtDisplayCenteredTextLine(5,"Oregon.");wait10Msec(10);}rdng=0;gx=40;read=1;}

if(rdng==2){eraseDisplay();
  nxtDisplayTextLine(1,"Annual Oregon ");
nxtDisplayCenteredTextLine(2,"Trail Race!");
nxtDisplayCenteredTextLine(4,"It's a race");
nxtDisplayCenteredTextLine(5,"to Oregon!");
wait1Msec(1000);
while(nNxtButtonPressed<=2){eraseDisplay();
nxtDisplayTextLine(1,"Annual Oregon ");
nxtDisplayCenteredTextLine(2,"Trail Race!");
nxtDisplayCenteredTextLine(4,"It's a race");
nxtDisplayCenteredTextLine(5,"to Oregon!");wait10Msec(10);}rdng=0;gx=40;read=2;}

}


while(nNxtButtonPressed>=1){}
cont=false;
CCC=50;
while(cont==false){eraseDisplay();

nxtDrawLine(33,0,33,15);
nxtDrawLine(66,0,66,15);
nxtDrawLine(CCC,16,CCC,25);
nxtDrawLine(CCC,16,CCC+4,20);
nxtDrawLine(CCC,16,CCC-4,20);

nxtDisplayCenteredTextLine(1,"Bronze");
nxtDisplayCenteredTextLine(2,"Bruzer");
if(wsn<=500){nxtDisplayCenteredTextLine(4,"toughness 15");}
else{if(WSN<=1000){nxtDisplayCenteredTextLine(4,"acceleration 12");}                                      //b
else{if(WSN<=1500){nxtDisplayCenteredTextLine(4,"speed 3");}
else{nxtDisplayCenteredTextLine(4,"steering 6");}}}

nxtDisplayStringAt(48,40,"10");


if(CCC<=66){
nxtDisplayCenteredTextLine(1,"Silver");
nxtDisplayCenteredTextLine(2,"Speeder");
nxtDisplayStringAt(48,40,"15");
if(wsn<=500){nxtDisplayCenteredTextLine(4,"toughness 6");}
else{if(WSN<=1000){nxtDisplayCenteredTextLine(4,"acceleration 9");}                                       //s
else{if(WSN<=1500){nxtDisplayCenteredTextLine(4,"speed 15");}
else{nxtDisplayCenteredTextLine(4,"steering 9");}}}
}

if(CCC<=33){
nxtDisplayCenteredTextLine(1,"Golden");
nxtDisplayCenteredTextLine(2,"Jet Wagon");
nxtDisplayStringAt(48,40,"20");
if(wsn<=500){nxtDisplayCenteredTextLine(4,"toughness 9");}
else{if(WSN<=1000){nxtDisplayCenteredTextLine(4,"acceleration 15");}                                      //g
else{if(WSN<=1500){nxtDisplayCenteredTextLine(4,"speed 12");}
else{nxtDisplayCenteredTextLine(4,"steering 9");}}}
}

nxtDisplayStringAt(40,40,"$");

nxtDrawLine(1,55,101,55);
nxtDisplayTextLine(0,"    choose wagon");
nxtDisplayStringAt(1,63,"$");
nxtDisplayStringAt(7,63,"%d",mun);

WSN=WSN+25;
if(WSN>=2000){WSN=0;}

if(nNxtButtonPressed==1){CCC=CCC+1;}
if(nNxtButtonPressed==2){CCC=CCC-1;}
if(nNxtButtonPressed==3){if(CCC<=33){if(mun>=20){mun=mun-20;GW=2;}}                                             //wagons
else{if(CCC<=66){if(mun>=15){mun=mun-15;SW=2;}}
else{if(mun>=10){mun=mun-10;BW=2;}}}cont=true;}

wait1Msec(50);
}
cont=false;

while(nNxtButtonPressed>=1){}

while(cont==false){eraseDisplay();

  nxtDrawLine(33,0,33,15);
nxtDrawLine(66,0,66,15);
nxtDrawLine(CCC,16,CCC,25);
nxtDrawLine(CCC,16,CCC+4,20);
nxtDrawLine(CCC,16,CCC-4,20);


nxtDisplayCenteredTextLine(2,"mines");
nxtDisplayCenteredTextLine(3,"$5");

if(CCC<=66){nxtDisplayCenteredTextLine(2,"rockets");
nxtDisplayCenteredTextLine(3,"$10");
}

if(CCC<=33){nxtDisplayCenteredTextLine(2,"boosts");
nxtDisplayCenteredTextLine(3,"$15");
}


nxtDrawLine(1,55,101,55);
nxtDisplayTextLine(0,"    choose weapon");
nxtDisplayStringAt(1,63,"$");
nxtDisplayStringAt(7,63,"%d",mun);


if(nNxtButtonPressed==1){CCC=CCC+1;}
if(nNxtButtonPressed==2){CCC=CCC-1;}
if(nNxtButtonPressed==3){if(CCC<=33){BWE=2;mun=mun-15;}else{if(CCC<=66){RWE=2;mun=mun-10;}else{MWE=2;mun=mun-5;}}cont=true;}

wait1Msec(50);

}

cont=false;
while(nNxtButtonPressed==3){}

while(cont==false){eraseDisplay();

  nxtDrawLine(20,0,20,15);
nxtDrawLine(40,0,40,15);
nxtDrawLine(60,0,60,15);
nxtDrawLine(80,0,80,15);
nxtDrawLine(CCC,16,CCC,25);
nxtDrawLine(CCC,16,CCC+4,20);
nxtDrawLine(CCC,16,CCC-4,20);

nxtDisplayStringAt(2,7,"%d",TP);
nxtDisplayStringAt(22,7,"%d",AP);
nxtDisplayStringAt(42,7,"%d",SP);
nxtDisplayStringAt(62,7,"%d",STP);

nxtDisplayCenteredTextLine(2,"done buying");
nxtDisplayCenteredTextLine(3,"perks");
if(CCC<=80){nxtDisplayCenteredTextLine(2,"steering");
nxtDisplayCenteredTextLine(3,"perk");}
if(CCC<=60){nxtDisplayCenteredTextLine(2,"speed");
nxtDisplayCenteredTextLine(3,"perk");}
if(CCC<=40){nxtDisplayCenteredTextLine(2,"acceleration");
nxtDisplayCenteredTextLine(3,"perk");}
if(CCC<=20){nxtDisplayCenteredTextLine(2,"toughness");
nxtDisplayCenteredTextLine(3,"perk");}

nxtDrawLine(1,55,101,55);
nxtDisplayTextLine(0,"    choose perks");
nxtDisplayStringAt(1,63,"$");
nxtDisplayStringAt(7,63,"%d",mun);


if(nNxtButtonPressed==1){CCC=CCC+1;}
if(nNxtButtonPressed==2){CCC=CCC-1;}
if(nNxtButtonPressed==3){if(PB==true){PB=false;if(CCC>=80){cont=true;}else{if(mun>=1){mun=mun-1;if(CCC>=60){STP=STP+1;}else{if(CCC>=40){SP=SP+1;}else{if(CCC>=20){AP=AP+1;}else{TP=TP+1;}}}}}}}
else{PB=true;}

wait1Msec(50);

}
cont=false;


STP=STP/120000;

eraseDisplay();

nNxtExitClicks = 3;

while(cont==false){


if(DN==5){eraseDisplay();

DXJ=XJ*2000;
DYJ=YJ*2000;
if(DXJ>=0){if(DYJ>=0){while(DXJ+DYJ>=500){DXJ=DXJ*0.9;DYJ=DYJ*0.9;}}else{while(DXJ+(DYJ*-1)>=500){DXJ=DXJ*0.9;DYJ=DYJ*0.9;}}}
else{if(DYJ>=0){while(DXJ*-1+DYJ>=500){DXJ=DXJ*0.9;DYJ=DYJ*0.9;}}else{while(DXJ*-1+(DYJ*-1)>=500){DXJ=DXJ*0.9;DYJ=DYJ*0.9;}}}

if(DXJ>=0){SDXJ=sqrt(DXJ);}else{SDXJ=sqrt(DXJ*-1);SDXJ=SDXJ*-1;}
if(DYJ>=0){SDYJ=sqrt(DYJ);}else{SDYJ=sqrt(DYJ*-1);SDYJ=SDYJ*-1;}


RCT1DXJ=RCT1XJ*200;
RCT1DYJ=RCT1YJ*200;
if(RCT1DXJ>=0){if(RCT1DYJ>=0){while(RCT1DXJ+RCT1DYJ>=8){RCT1DXJ=RCT1DXJ*0.9;RCT1DYJ=RCT1DYJ*0.9;}}else{while(RCT1DXJ+(RCT1DYJ*-1)>=8){RCT1DXJ=RCT1DXJ*0.9;RCT1DYJ=RCT1DYJ*0.9;}}}
else{if(RCT1DYJ>=0){while(RCT1DXJ*-1+RCT1DYJ>=8){RCT1DXJ=RCT1DXJ*0.9;RCT1DYJ=RCT1DYJ*0.9;}}else{while(RCT1DXJ*-1+(RCT1DYJ*-1)>=8){RCT1DXJ=RCT1DXJ*0.9;RCT1DYJ=RCT1DYJ*0.9;}}}

nxtDrawLine(X+SDXJ,Y+SDYJ,X,Y);
//nxtDrawLine(X-SDYJ+SDXJ,Y+SDXJ+SDYJ,X+SDYJ-SDXJ,Y-SDXJ-SDYJ);
nxtFillEllipse(X-2,Y-2,X+2,Y+2);

nxtDrawLine(AX+100,65,AX+100,-1);
nxtDrawLine(AX-100,65,AX-100,-1);
//nxtDrawRect(AX-100,AY+100,AX+100,AY-100);
//nxtDrawRect(AX-30,AY+30,AX+30,AY-30);

nxtFillEllipse(T1X+10,T1Y+10,T1X-10,T1Y-10);
nxtFillEllipse(T2X+10,T2Y+10,T2X-10,T2Y-10);

nxtDrawRect(MX+5,MY+5,MX-5,MY-5);
nxtDisplayStringAt(MX-3,MY,"%d",DMT);
if(DMT<=0){nxtFillEllipse(MX+50,MY+50,MX-50,MY-50);}

nxtDrawLine(w1x1,w1y1,w1x2,w1y2);

nxtDrawRect(jp1x+5,jp1y+5,jp1x-5,jp1y-5);
nxtDisplayStringAt(jp1x-2,jp1y+4,"J");

nxtDrawRect(CB1X+5,CB1Y+5,CB1X-5,CB1Y-5);
nxtDrawLine(CB1X,CB1Y-3,CB1X,CB1Y+3);
nxtDrawLine(CB1X,CB1Y+3,CB1X-3,CB1Y);
nxtDrawLine(CB1X,CB1Y+3,CB1X+3,CB1Y);

if(ex1n>=2500){nxtDrawLine(ex1X+5,ex1Y+5,ex1X-5,ex1Y-5);nxtDrawLine(ex1X-5,ex1Y+5,ex1X+5,ex1Y-5);nxtDrawLine(ex1X,ex1Y+7,ex1X,ex1Y-7);nxtDrawLine(ex1X+7,ex1Y,ex1X-7,ex1Y);}

nxtFillRect(AX+500,AY+1000,AX-500,AY+1100);

nxtDrawRect(dot1x,dot1y,dot1x,dot1y);
nxtDrawRect(dot2x,dot2y,dot2x,dot2y);
nxtDrawRect(dot3x,dot3y,dot3x,dot3y);
nxtDrawRect(dot4x,dot4y,dot4x,dot4y);

nxtDrawLine(RCT1x+RCT1DXJ,RCT1y+RCT1DYJ,RCT1x,RCT1y);

nxtDisplayTextLine(0,"speed");
nxtDisplayStringAt(37,63,"%d",Ispd);
nxtDisplayStringAt(48,63,"/")
if(GW==2){nxtDisplayStringAt(53,63,"%d", 12+SP);}
if(SW==2){nxtDisplayStringAt(53,63,"%d", 15+SP);}
if(BW==2){nxtDisplayStringAt(53,63,"%d", 3+SP);}

nxtDisplayStringAt(2,54,"%d",DRT);

}
DN=DN-1;
if(DN<=0){DN=6}

if(Y>=15){Y=Y-1;AY=AY-1;T1Y=T1Y-1;T2Y=T2Y-1;CB1Y=CB1Y-1;w1y1=w1y1-1;w1y2=w1y2-1;dot1y=dot1y-1;dot2y=dot2y-1;dot3y=dot3y-1;dot4y=dot4y-1;ex1y=ex1y-1;jp1y=jp1y-1;RCT1y=RCT1y-1;MY=MY-1;}
if(Y<=5){Y=Y+1;AY=AY+1;T1Y=T1Y+1;T2Y=T2Y+1;CB1Y=CB1Y+1;w1y1=w1y1+1;w1y2=w1y2+1;dot1y=dot1y+1;dot2y=dot2y+1;dot3y=dot3y+1;dot4y=dot4y+1;ex1y=ex1y+1;jp1y=jp1y+1;RCT1y=RCT1y+1;MY=MY+1;}
if(X>=55){X=X-1;AX=AX-1;T1X=T1X-1;T2X=T2X-1;CB1X=CB1X-1;w1x1=w1x1-1;w1x2=w1x2-1;dot1x=dot1x-1;dot2x=dot2x-1;dot3x=dot3x-1;dot4x=dot4x-1;ex1x=ex1x-1;jp1x=jp1x-1;RCT1x=RCT1x-1;MX=MX-1;}
if(X<=45){X=X+1;AX=AX+1;T1X=T1X+1;T2X=T2X+1;CB1X=CB1X+1;w1x1=w1x1+1;w1x2=w1x2+1;dot1x=dot1x+1;dot2x=dot2x+1;dot3x=dot3x+1;dot4x=dot4x+1;ex1x=ex1x+1;jp1x=jp1x+1;RCT1x=RCT1x+1;MX=MX+1;}

if(T1Y<=-20){T1Y=random(50)+80;T1X=AX+random(200)-100;}
if(T2Y<=-20){T2Y=random(50)+80;T2X=AX+random(200)-100;}

if(CB1Y<=-20){CB1X=AX+random(200)-100;CB1Y=random(50)+80;}

if(X<=Jp1x+5){if(X>=Jp1x-5){if(Y>=Jp1y-5){if(Y<=Jp1y+5){aiti=1000;}}}}

aiti=aiti-1;

if(RT>=1){RT=RT-1;}
DRT=RT/1000;

if(X>=AX+100){X=AX+99;}
if(X<=AX-100){X=AX-99;}

if(aiti<=0){

if(w1x1>=w1x2){if(w1y1>=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-X)/(w1y1-Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-X)/(w1y1-Y)-0.15){if(X<=w1x1){if(X>=w1x2){if(Y<=w1y1){if(Y>=w1y2){
spd=0;X=X-Xj;Y=Y-Yj;ddot1=true;ddot2=true;}}}}}}}}//
if(w1x1<=w1x2){if(w1y1<=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-X)/(w1y1-Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-X)/(w1y1-Y)-0.15){if(X<=w1x2){if(X>=w1x1){if(Y<=w1y2){if(Y>=w1y1){
spd=0;X=X-Xj;Y=Y-Yj;ddot1=true;ddot2=true;}}}}}}}}//
if(w1x1<=w1x2){if(w1y1>=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-X)/(w1y1-Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-X)/(w1y1-Y)-0.15){if(X<=w1x2){if(X>=w1x1){if(Y<=w1y1){if(Y>=w1y2){
spd=0;X=X-Xj;Y=Y-Yj;ddot1=true;ddot2=true;}}}}}}}}//
if(w1x1>=w1x2){if(w1y1<=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-X)/(w1y1-Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-X)/(w1y1-Y)-0.15){if(X<=w1x1){if(X>=w1x2){if(Y<=w1y2){if(Y>=w1y1){
spd=0;X=X-Xj;Y=Y-Yj;ddot1=true;ddot2=true;}}}}}}}}//

if(X>=CB1X-5){if(X<=CB1X+5){if(Y>=CB1Y-5){if(Y<=CB1Y+5){spd=spd+30000;CB1X=AX+random(200)-100;CB1Y=random(50)+80;}}}}

if(w1y1<=-20){if(w1y2<=-20){w1cx=random(200)-100+AX;w1cy=random(200)+(Y+100);w1x1=random(70)+w1cx;w1y1=random(70)+w1cy;w1x2=random(70)+w1cx;w1y2=random(70)+w1cy;}}

}

dot1x=dot1x+dot1xj;
dot1y=dot1y+dot1yj;
dot2x=dot2x+dot2xj;
dot2y=dot2y+dot2yj;
dot3x=dot3x+dot3xj;
dot3y=dot3y+dot3yj;
dot4x=dot4x+dot4xj;
dot4y=dot4y+dot4yj;

//if(XJ!=0){if(XJ>=0){XJ=sqrt(XJ);}else{XJ=XJ*-1;XJ=sqrt(XJ);XJ=XJ*-1;}}
//if(YJ!=0){if(YJ>=0){YJ=sqrt(YJ);}else{YJ=YJ*-1;YJ=sqrt(YJ);YJ=YJ*-1;}}
X=X+sXJ*spd/100000;
Y=Y+sYJ*spd/100000;
//if(XJ>=0.0001){XJ=XJ-0.00005;}
//if(XJ<=-0.0001){XJ=XJ+0.00005;}
//XJ=XJ*XJ;YJ=YJ*YJ;


Ispd=spd/10000;
if(GW==2){if(Ispd>=13+SP){spd=spd-100;}}
if(SW==2){if(Ispd>=16+SP){spd=spd-100;}}
if(BW==2){if(Ispd>=4+SP){spd=spd-100;}}

if(ddot1==true){dot1x=x;dot1y=y;dot1xj=random(100)-50;dot1yj=random(100)-50;ddot1=false;dot1xj=dot1xj/500;dot1yj=dot1yj/500;
dot2x=x;dot2y=y;dot2xj=random(100)-50;dot2yj=random(100)-50;ddot2=false;dot2xj=dot2xj/500;dot2yj=dot2yj/500;
dot3x=x;dot3y=y;dot3xj=random(100)-50;dot3yj=random(100)-50;ddot3=false;dot3xj=dot3xj/500;dot3yj=dot3yj/500;
dot4x=x;dot4y=y;dot4xj=random(100)-50;dot4yj=random(100)-50;dot4xj=dot4xj/500;dot4yj=dot4yj/500;
if(ex1n<=0){ex1x=x;ex1y=y;ex1n=3500;}    }

if(jp1y<=-20){jp1y=random(200)+75;jp1x=random(200)+AX-100;}


MT=MT-1;
if(MT<=0){DMT=DMT-1;MT=1000;}
if(DMT<=-1){MX=500;}

if(XJ>=0){sXJ=sqrt(XJ);}else{sXJ=sqrt(XJ*-1);sXJ=sXJ*-1;}
if(YJ>=0){sYJ=sqrt(YJ);}else{sYJ=sqrt(YJ*-1);sYJ=sYJ*-1;}

ex1n=ex1n-2;

RCT1X=RCT1X+RCT1XJ;RCT1Y=RCT1Y+RCT1YJ;

tme=tme +1;
Dtme=tme/1000;

if(aiti<=0){

if(BW==2){if(T1X-X>=0){if(T1Y-Y>=0){if(T1X-X+T1Y-Y<=13){X=X-(T1X-X)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}
else{if(T1X-X+Y-T1Y<=13){X=X-(T1X-X)/11;Y=Y+1;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}}
else{if(T1Y-Y>=0){if(X-T1X+T1Y-Y<=13){X=X+(X-t1x)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}
else{if(X-T1X+Y-T1Y<=13){X=X+(X-t1X)/11;Y=Y+(Y-t1Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}}}
if(SW==2){if(T1X-X>=0){if(T1Y-Y>=0){if(T1X-X+T1Y-Y<=13){X=X-(T1X-X)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}
else{if(T1X-X+Y-T1Y<=13){X=X-(T1X-X)/11;Y=Y+1;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}}
else{if(T1Y-Y>=0){if(X-T1X+T1Y-Y<=13){X=X+(X-t1x)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}
else{if(X-T1X+Y-T1Y<=13){X=X+(X-t1X)/11;Y=Y+(Y-t1Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}}}
if(GW==2){if(T1X-X>=0){if(T1Y-Y>=0){if(T1X-X+T1Y-Y<=13){X=X-(T1X-X)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}
else{if(T1X-X+Y-T1Y<=13){X=X-(T1X-X)/11;Y=Y+1;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}}
else{if(T1Y-Y>=0){if(X-T1X+T1Y-Y<=13){X=X+(X-t1x)/11;Y=Y-(T1Y-Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}
else{if(X-T1X+Y-T1Y<=13){X=X+(X-t1X)/11;Y=Y+(Y-t1Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}}}

if(BW==2){if(T2X-X>=0){if(T2Y-Y>=0){if(T2X-X+T2Y-Y<=13){X=X-(T2X-X)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}
else{if(T2X-X+Y-T2Y<=13){X=X-(T2X-X)/11;Y=Y+1;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}}
else{if(T2Y-Y>=0){if(X-T2X+T2Y-Y<=13){X=X+(X-t2x)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}
else{if(X-T2X+Y-T2Y<=13){X=X+(X-t2X)/11;Y=Y+(Y-t1Y)/11;spd=spd-(100000/(TP+15));ddot1=true;ddot2=true;}}}}
if(SW==2){if(T2X-X>=0){if(T2Y-Y>=0){if(T2X-X+T2Y-Y<=13){X=X-(T2X-X)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}
else{if(T2X-X+Y-T2Y<=13){X=X-(T2X-X)/11;Y=Y+1;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}}
else{if(T2Y-Y>=0){if(X-T2X+T2Y-Y<=13){X=X+(X-t2x)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}
else{if(X-T2X+Y-T2Y<=13){X=X+(X-t2X)/11;Y=Y+(Y-t2Y)/11;spd=spd-(100000/(TP+6));ddot1=true;ddot2=true;}}}}
if(GW==2){if(T2X-X>=0){if(T2Y-Y>=0){if(T2X-X+T2Y-Y<=13){X=X-(T2X-X)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}
else{if(T2X-X+Y-T2Y<=13){X=X-(T2X-X)/11;Y=Y+1;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}}
else{if(T2Y-Y>=0){if(X-T2X+T2Y-Y<=13){X=X+(X-t2x)/11;Y=Y-(T2Y-Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}
else{if(X-T2X+Y-T2Y<=13){X=X+(X-t2X)/11;Y=Y+(Y-t2Y)/11;spd=spd-(100000/(TP+9));ddot1=true;ddot2=true;}}}}

}

if(T1X-RCT1x>=0){if(T1Y-RCT1Y>=0){if(T1X-RCT1X+T1Y-RCT1Y<=13){ T1Y=random(50)+80;T1X=AX+random(200)-100;RCT1x=300;}}
else{if(T1X-RCT1X+RCT1Y-T1Y<=13){ T1Y=random(50)+80;T1X=AX+random(200)-100;RCT1x=300;}}}
else{if(T1Y-RCT1Y>=0){if(RCT1X-T1X+T1Y-RCT1Y<=13){ T1Y=random(50)+80;T1X=AX+random(200)-100;RCT1x=300;}}
else{if(RCT1X-T1X+RCT1Y-T1Y<=13){ T1Y=random(50)+80;T1X=AX+random(200)-100;RCT1x=300;}}}

if(T2X-RCT1x>=0){if(T2Y-RCT1Y>=0){if(T2X-RCT1X+T2Y-RCT1Y<=13){ T2Y=random(50)+80;T2X=AX+random(200)-100;RCT1x=300;}}
else{if(T2X-RCT1X+RCT1Y-T2Y<=13){ T2Y=random(50)+80;T2X=AX+random(200)-100;RCT1x=300;}}}
else{if(T2Y-RCT1Y>=0){if(RCT1X-T2X+T2Y-RCT1Y<=13){ T2Y=random(50)+80;T2X=AX+random(200)-100;RCT1x=300;}}
else{if(RCT1X-T2X+RCT1Y-T2Y<=13){ T2Y=random(50)+80;T2X=AX+random(200)-100;RCT1x=300;}}}

if(w1x1>=w1x2){if(w1y1>=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-RCT1x)/(w1y1-RCT1Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-RCT1X)/(w1y1-RCT1Y)-0.15){if(RCT1X<=w1x1){if(X>=w1x2){if(RCT1Y<=w1y1){if(RCT1Y>=w1y2){
W1Y1=-100;W1Y2=-100;RCT1X=300;}}}}}}}}//
if(w1x1<=w1x2){if(w1y1<=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-RCT1X)/(w1y1-RCT1Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-RCT1X)/(w1y1-RCT1Y)-0.15){if(RCT1X<=w1x2){if(RCT1X>=w1x1){if(RCT1Y<=w1y2){if(RCT1Y>=w1y1){
W1Y1=-100;W1Y2=-100;RCT1X=300;}}}}}}}}//
if(w1x1<=w1x2){if(w1y1>=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-RCT1X)/(w1y1-RCT1Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-RCT1X)/(w1y1-RCT1Y)-0.15){if(RCT1X<=w1x2){if(RCT1X>=w1x1){if(RCT1Y<=w1y1){if(RCT1Y>=w1y2){
W1Y1=-100;W1Y2=-100;RCT1X=300;}}}}}}}}//
if(w1x1>=w1x2){if(w1y1<=w1y2){if((w1x1-w1x2)/(w1y1-w1y2)<=(w1x1-RCT1X)/(w1y1-RCT1Y)+0.15){if((w1x1-w1x2)/(w1y1-w1y2)>=(w1x1-RCT1X)/(w1y1-RCT1Y)-0.15){if(RCT1X<=w1x1){if(RCT1X>=w1x2){if(RCT1Y<=w1y2){if(RCT1Y>=w1y1){
W1Y1=-100;W1Y2=-100;RCT1X=300;}}}}}}}}//


if(Y>=AY+1001){eraseDisplay();nxtDisplayCenteredTextLine(2,"time"); nxtDisplayStringAt(10,30,"%d",Dtme);wait1Msec(10000);}

if(BWE>=2){
if(SensorValue(T)==1){if(DRT<=0){RT=5000;spd=spd+30000;}}
}
if(RWE>=2){
if(SensorValue(T)==1){if(DRT<=0){RT=5000;RCT1x=X;RCT1y=Y;RCT1XJ=XJ*3;RCT1YJ=YJ*3;}}
}
if(MWE>=2){
if(SensorValue(T)==1){if(DRT<=0){RT=5000;MX=X;MY=Y;MT=1000;DMT=3;}}
}


if(aiti<=0){
if(BW!=2){
if(nNxtButtonPressed==2){if(XJ>=0){if(YJ>=0){XJ=XJ-(0.000075+STP);YJ=YJ+(0.000075+STP);}else{YJ=YJ+(0.000075+STP);XJ=XJ+(0.000075+STP);}}else{if(YJ>=0){YJ=YJ-(0.000075+STP);XJ=XJ-(0.000075+STP);}else{YJ=YJ-(0.000075+STP);XJ=XJ+(0.000075+STP);}}} // Clockwise
if(nNxtButtonPressed==1){if(XJ>=0){if(YJ>=0){XJ=XJ+(0.000075+STP);YJ=YJ-(0.000075+STP);}else{YJ=YJ-(0.000075+STP);XJ=XJ-(0.000075+STP);}}else{if(YJ>=0){YJ=YJ+(0.000075+STP);XJ=XJ+(0.000075+STP);}else{YJ=YJ+(0.000075+STP);XJ=XJ-(0.000075+STP);}}} // CounterClockwise
}else{
if(nNxtButtonPressed==2){if(XJ>=0){if(YJ>=0){XJ=XJ-(0.00005+STP);YJ=YJ+(0.00005+STP);}else{YJ=YJ+(0.00005+STP);XJ=XJ+(0.00005+STP);}}else{if(YJ>=0){YJ=YJ-(0.00005+STP);XJ=XJ-(0.00005+STP);}else{YJ=YJ-(0.00005+STP);XJ=XJ+(0.00005+STP);}}} // Clockwise
if(nNxtButtonPressed==1){if(XJ>=0){if(YJ>=0){XJ=XJ+(0.00005+STP);YJ=YJ-(0.00005+STP);}else{YJ=YJ-(0.00005+STP);XJ=XJ-(0.00005+STP);}}else{if(YJ>=0){YJ=YJ+(0.00005+STP);XJ=XJ+(0.00005+STP);}else{YJ=YJ+(0.00005+STP);XJ=XJ-(0.00005+STP);}}} // CounterClockwise
}
//if(nNxtButtonPressed==1){if(XJ<=8){if(XJ>=-8){if(GW==2){XJ=XJ+(0.0001875+STP);}if(SW==2){XJ=XJ+(0.0001875+STP);}if(BW==2){XJ=XJ+(0.000125+STP);}}}}
//if(nNxtButtonPressed==2){if(XJ<=8){if(XJ>=-8){if(GW==2){XJ=XJ-(0.0001875+STP);}if(SW==2){XJ=XJ-(0.0001875+STP);}if(BW==2){XJ=XJ-(0.000125+STP);}}}}
if(nNxtButtonPressed==3){if(GW==2){spd=spd+9+AP;}if(SW==2){spd=spd+9+AP;}if(BW==2){spd=spd+12+AP;}}
if(nNxtButtonPressed==0){if(spd>=0){spd=spd-1000;}}

}

wait1Msec(1);
}






}
